### ISSUE TITLE
Regular meeting schedule

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/debugging#4]
Let's start having more regular subgroup meetings.
Other CG meetings are biweekly, for an hour at a time.
Is that too often?

Just to get a general sense, here's a [doodle](https://doodle.com/poll/4aty7d2f8q7kzx45#calendar) where you can indicate preferences. It includes *2 weeks* because at least my schedule is quite different on alternate weeks. If we decide to go monthly I can make a separate doodle, or just figure it out from this one.

(Actually Sep 2 is a US holiday, but I just filled in the doodle as if it weren't).

**Comment by dschuff** [comment]
Based on the results, it looks like Thursday, 5 September at 11:00 AM PST/20:00 CET is a pretty clear winner. I'll set up something biweekly for now; let's follow the other wasm groups in requesting that people add something to the agenda ahead of time via a PR, so we can cancel the meeting if there are no topics.

**Comment by dschuff** [comment]
I've created a calendar invite with everyone who has participated in the previous meeting. Let me know if you are not on the invite and want to be.

**Comment by codehag** [comment]
It is impossible for me to attend at the chosen time (8-9pm cest). Unfortunately I didn't see the doodle on time to vote...
